version: "2.0"

services:

  backend:
    image: docker-test
    container_name: test-docker-container
    build:
      context: ./
    ports:
      - "3744:3744"
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5437:5432"