spring:
  application:
    name: Test
  profiles:
    active: local

server:
  port: 3744

---

spring:
  profiles: local
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

---

#Fix Postgres JPA Error
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
